apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-read-config
spec:
  workspaces:
    - name: output
      description: shared workspace  
  params:
    - name: test-param
      description: test-param
  steps:
    - name: task-read-config
      image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.6
      script: |
        #!/bin/bash
        echo "task-read-config"
        pwd
        env
        trap env EXIT
        set -x